apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-deployment-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: default
roleRef:
  kind: Role
  name: flux-deployment-manager
  apiGroup: rbac.authorization.k8s.io
