name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY }}/custom-nginx:latest .
          docker push ${{ secrets.AZURE_REGISTRY }}/custom-nginx:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_UPDATED }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group clustrg --name practiceaks

      - name: Deploy to AKS
        run: |
          kubectl apply -f nginx-deployment.yaml
          kubectl apply -f nginx-service.yaml
